app: hpuApi_sls
component: express
name: expressDemo
inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-beijing
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - https
    environment: release
  functionConf:
    eip: false
    timeout: 8
    memorySize: 128
    environment:
      variables:
        NODE_ENV: production