org: hpuApi
app: hpuApi
stage: dev
component: scf
name: main
inputs:
  src:
    src: ./
    exclude:
      - .env
      - test/**
      - temp.jpg
      - node_modules/**
      - tf-model/**
  handler: tencent_sls.handler
  region: ap-guangzhou
  runtime: Nodejs12.16
  eip: false
  timeout: 10
  memorySize: 1024
  environment:
    variables:
      NODE_ENV: production