org: orgDemo
app: hpuApi_sls
stage: dev
component: express
name: expressDemo
inputs:
  src:
    src: ./
    exclude:
      - .env
      - test/**
      - temp.jpg
      - node_modules/**
      - tf-model/**
  layers:
    - name: ${output:${stage}:${app}:${name}-layer.name}
      version: ${output:${stage}:${app}:${name}-layer.version}
  region: ap-beijing
  runtime: Nodejs12.16
  apigatewayConf:
    protocols:
      - https
    environment: release
  functionConf:
    eip: false
    timeout: 8
    memorySize: 128
    environment:
      variables:
        NODE_ENV: production