const cv = require('opencv4nodejs-prebuilt');
const {uia_request} = require('../request')

function templateMatch(numImg) {
    // bmp files
    const common = 'Qk3qBAAAAAAAADYEAAAoAAAACgAAAA8AAAABAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQACAgIAAwMDAAQEBAAFBQUABgYGAAcHBwAICAgACQkJAAoKCgALCwsADAwMAA0NDQAODg4ADw8PABAQEAAREREAEhISABMTEwAUFBQAFRUVABYWFgAXFxcAGBgYABkZGQAaGhoAGxsbABwcHAAdHR0AHh4eAB8fHwAgICAAISEhACIiIgAjIyMAJCQkACUlJQAmJiYAJycnACgoKAApKSkAKioqACsrKwAsLCwALS0tAC4uLgAvLy8AMDAwADExMQAyMjIAMzMzADQ0NAA1NTUANjY2ADc3NwA4ODgAOTk5ADo6OgA7OzsAPDw8AD09PQA+Pj4APz8/AEBAQABBQUEAQkJCAENDQwBEREQARUVFAEZGRgBHR0cASEhIAElJSQBKSkoAS0tLAExMTABNTU0ATk5OAE9PTwBQUFAAUVFRAFJSUgBTU1MAVFRUAFVVVQBWVlYAV1dXAFhYWABZWVkAWlpaAFtbWwBcXFwAXV1dAF5eXgBfX18AYGBgAGFhYQBiYmIAY2NjAGRkZABlZWUAZmZmAGdnZwBoaGgAaWlpAGpqagBra2sAbGxsAG1tbQBubm4Ab29vAHBwcABxcXEAcnJyAHNzcwB0dHQAdXV1AHZ2dgB3d3cAeHh4AHl5eQB6enoAe3t7AHx8fAB9fX0Afn5+AH9/fwCAgIAAgYGBAIKCggCDg4MAhISEAIWFhQCGhoYAh4eHAIiIiACJiYkAioqKAIuLiwCMjIwAjY2NAI6OjgCPj48AkJCQAJGRkQCSkpIAk5OTAJSUlACVlZUAlpaWAJeXlwCYmJgAmZmZAJqamgCbm5sAnJycAJ2dnQCenp4An5+fAKCgoAChoaEAoqKiAKOjowCkpKQApaWlAKampgCnp6cAqKioAKmpqQCqqqoAq6urAKysrACtra0Arq6uAK+vrwCwsLAAsbGxALKysgCzs7MAtLS0ALW1tQC2trYAt7e3ALi4uAC5ubkAurq6ALu7uwC8vLwAvb29AL6+vgC/v78AwMDAAMHBwQDCwsIAw8PDAMTExADFxcUAxsbGAMfHxwDIyMgAycnJAMrKygDLy8sAzMzMAM3NzQDOzs4Az8/PANDQ0ADR0dEA0tLSANPT0wDU1NQA1dXVANbW1gDX19cA2NjYANnZ2QDa2toA29vbANzc3ADd3d0A3t7eAN/f3wDg4OAA4eHhAOLi4gDj4+MA5OTkAOXl5QDm5uYA5+fnAOjo6ADp6ekA6urqAOvr6wDs7OwA7e3tAO7u7gDv7+8A8PDwAPHx8QDy8vIA8/PzAPT09AD19fUA9vb2APf39wD4+PgA+fn5APr6+gD7+/sA/Pz8AP39/QD+/v4A////';
    const templateImg = [
        'AAUAAAD9/wEAAAEAAAAB//7/////AQEAAAAA/QAEAPz+AAAAAAD+/wMAAwP//wEAAAD//gACAAH8/wAAAAP9/wIAAQD//wAAAAD/AAADAAH+/QMAAAH8AwEAAgD+/QMAAAH/+QADAAL+/wAAAAD//wAAAQD//wAAAAH//wACAAD//wEAAAD+/gEAAgD+AAAAAAD//f/7///9AQEAAAAA/P///v4BAAEAAAAAAQEAAgAAAgAAAA==',
        'AAAAAAD//wAAAAAAAAAAAAD//wAAAAAAAAAAAAD//wAAAAAAAAAAAAD//wAAAAAAAAAAAAD//wAAAAAAAAAAAAD//wAAAAAAAAAAAAD//wAAAAAAAAADAAD//wABAAAAAAAAAAL//gAAAAAAAAEAAQD//QEAAAAAAAMA/v/8/wAAAAAAAAACAf///wADAAAAAAAAAAD6/wAAAAAAAAQAAAED+QUAAAAAAAAAAgAAAwAAAAAAAA==',
        'AAD///3+//7//gEAAAD///3///3+/wAAAAAB/f//AAADAAIAAAIAAPz+AgAAAwAAAAAAAgH/AAAAAAAAAAABAAH8/wMAAAEAAAABAAEA//4AAAMAAAAAAQQAAP/9AAMAAAEAAAADA///AQAAAAAGAAIAAAD//gQAAAP7AQEAAAD//wAAAAD+/wAAAAL+/gAAAAEA//7//v/+AQEAAAEBAP/9/v8AAAAAAAEABAABAAABAAAAAA==',
        'AAIAAP/+/AACAAEAAAAB//3//v/9AgAAAAD/+wQAAAD/AAMAAAH9AgACBAH+/wEAAAADAAAEAAD//QIAAAAAAgIAAQD//wAAAAEAAAABAP//AAIAAAAEAAH//f8AAQAAAAAAAgAAAf//AQAAAAMAAQABAf/9AAAAAAD+AAIAAAD//wAAAAD//wAABgD//wAAAAAD/P8AAP/+AAAAAAIAAf7//f8AAQAAAAABAAAAAAABAQAAAA==',
        'AAABAAMAAP7/AAAAAAABAAABAf3/AAAAAAMAAgACAf3+AAAAAP3////8///9//8AAP/9/v7//f/+//8AAAD/AQIAAfz/AAAAAAH//AEAAP/+AAAAAAAA//8A/f7/AAAAAAACAP//AP/9AAAAAAADAAH//vz/AAAAAAAAAQD+///6AAAAAAMAAAEB/v7/AAAAAAAAAAAAAf7/AAAAAAEBAQACAP/7AAAAAAEAAQABAAACAAAAAA==',
        'AAABAP///wEAAAEAAAD//v/5///+AQEAAAD/AAADAP//AAAAAP/7AQEAAgD9/wEAAAAAAgABAAD//wAAAAACAAABAAH+/wAAAAAAAQABAQD//QMAAAD//gAAAP//AAAAAAT8/v/9//8AAAAAAAD9/wAAAQIAAAAAAAIA/wD/AAABAAAAAAAA/AMAAgAAAAAAAAEB//z+////AAAAAAAD+//+/f/9AAAAAAEAAQABAAABAAAAAA==',
        'AAABAP/6//8BAAAAAAAA/////P3/AAIAAAD/+QADAAD//wAAAAH+/wAAAAEA/AQAAAEAAAIAAgAA/wEAAAD9/wEAAAIA/wAAAAD//wAAAAH//wAAAAH9/gEABPz//wEAAAEB////AP//AQEAAAAAAv0AAgAAAAAAAAEAAP//AgAEAQEAAAABAgD//gAAAAAAAAMBAAAA/wIAAgEAAAABAgAF//0BAAIAAAEAAAEAAAEAAAMAAA==',
        'AAEAAf3/AAIBAAAAAAEAAP//AAAAAAAAAAAAAP/9AwADAAAAAAEAAwD+AAAAAAAAAAAAAAP/AQABAAAAAAIAAwD9/QMAAAAAAAAFAAAD/wAAAAAAAAABAAIA//4AAwAAAAEAAgAAAP8AAAEAAAABAAEAAP/7AgAAAAABAAAABAD/AAMAAAIAAgAAAAD//wEAAAD////9///+/QIAAAP+/v/////+/wAAAAABAQABAQABAAIAAA==',
        'AAEAAP3//P8AAQAAAAD///7+////AAEAAAP8/AD+AwD//gAAAAD/AAEAAAL+/wAAAAD7AgEAAgD+/wUAAAH/AAADAQD///0AAAD7//8AAP/9AAMAAAD+/////v/+AQAAAAH//f8AAP//AAMAAAH//wECAAL8AQAAAAL7AAABAAD//QQAAAD//wEBAAL9AAAAAAEA/v4A////AAQAAAAABf/6//0AAQAAAAABAAABAAACAAAAAA==',
        'AAABAPwAAAIAAAAAAAEBAv///QACAAAAAAABAAD8/wAAAAAAAAAAAAH//AMBAAAAAAIAAQIA//0AAAAAAAADAPv//P8EAAAAAAP7///////9AAAAAAD//wAAAv3/AAIAAP/7AAAAAQD//wAAAP//AAMAAQH9/wAAAP78AAAAAAP//wAAAAD//AACAAD9/wAAAAD////+///+/QQAAAMAA/z////+AAAAAAADAAAEAAACAAIAAA=='
    ];

    let result = [], max = {v: -1, i: 0};
    for (const template of templateImg) {
        const mat = cv.imdecode(new Buffer.from(common+template, 'base64'), cv.IMREAD_GRAYSCALE);
        result.push(numImg.matchTemplate(mat, cv.TM_CCOEFF_NORMED).minMaxLoc()['minVal']);
    }
    for (let i = 0; i < result.length; i++) {
        if(result[i]>max.v) {
            max.v = result[i];
            max.i = i;
        }
    }
    
    return max.i;
}

module.exports = async function(req) {
    if(!req) req={};

    ret = await uia_request({
        method: 'GET',
        uri: '/sso/apis/v2/open/captcha'
    });
    
    if(!ret.data.img) return { body: { code: -1002, msg: '未知错误' }};
    const mat = cv.imdecode(new Buffer.from(ret.data.img, 'base64'), cv.IMREAD_COLOR).cvtColor(cv.COLOR_BGR2GRAY).threshold(230, 255, cv.THRESH_BINARY_INV);
    
    return {
        body: {
            code: 0,
            ...ret.data,
            captcha: templateMatch(mat.getRegion(new cv.Rect(20,5,10,15)))+templateMatch(mat.getRegion(new cv.Rect(40,5,10,15))),
        }
    }
}